// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghczhzfywivhrcvncffl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdoY3poemZ5d2l2aHJjdm5jZmZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5ODg3NTgsImV4cCI6MjA3MzU2NDc1OH0.U7hXgMuDSflmGUfZ0l_rbnUMqsT8G-5H9yenN_d-WgU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});